- dev/readme.extra/changelog.txt
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/AbstractGetAction.java
- src/main/java/com/compuware/ispw/restapi/action/AbstractPostAction.java
- src/main/java/com/compuware/ispw/restapi/action/SetInfoPostAction.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
CWE-124457 - Jenkins Operations Plugin - Bad error message when selected
host connection doesn't have a CES URL
CWE-126841 - ISPW Operations Jenkins Plugin has problems with
GetReleaseTaskList
CWE-124623 - Jenkins Operations Plugin - Pre-populate help text in
Request field
> CWE-124457 - Jenkins Operations Plugin - Bad error message when selected host connection doesn't have a CES URL

- pom.xml
- src/main/java/com/compuware/ispw/model/rest/SetInfo.java
- src/main/java/com/compuware/ispw/restapi/Constants.java
- src/main/java/com/compuware/ispw/restapi/IspwContextPathBean.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/DeployAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/DeployReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/GenerateTasksInAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/GenerateTasksInReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/IAction.java
- src/main/java/com/compuware/ispw/restapi/action/PromoteAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/PromoteReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/RegressAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/RegressReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/SetInfoPostAction.java
- src/main/webapp/help-ispwRequestBody.html
CWE-124529 - Jenkins Operations Plugin - use latest Compuware Common Configurations 1.0.4
CWE-125246 - Jenkins Operations Plugin - Task Operations - Generate/Promote/Regress/Deploy for both Assignments and Release
Additional:
* allow override field for promote
* freestyle build to detect not only set close but also set complete.
> Cwe 125246   jenkins operations plugin   task operations   generate/promote/regress/deploy/fallback for both assignments and release

- .gitignore
- README.md
- dev/readme.extra/changelog.txt
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/GetSetTaskListAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/util/HttpClientUtil.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
- src/main/webapp/help-ispwAction.html
- src/main/webapp/help-ispwRequestBody.html
Added the ability to retrieve a Set's list of tasks
Changes to logging to improve consistency and readability
> Added support for retrieving the task list for a ISPW Set.

- src/main/java/com/compuware/ispw/restapi/HttpRequestExecution.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/AbstractGetAction.java
- src/main/java/com/compuware/ispw/restapi/action/AbstractPostAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/action/SetInfoPostAction.java
- src/main/java/com/compuware/ispw/restapi/util/ReflectUtils.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
instantiating ISPW actions for Jenkins ISPW Operations Plugin
> CWE-141872 - Refactor to use Java annotation and reflection to simply

- src/main/java/com/compuware/ispw/model/rest/MultiTaskFailure.java
- src/main/java/com/compuware/ispw/model/rest/MultiTaskInfoResponse.java
- src/main/java/com/compuware/ispw/model/rest/TransferTaskInfo.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/action/TransferTaskAction.java
- src/main/webapp/help-ispwRequestBody.html
> CWE-130837 - Jenkins Operations Plug-In - Add Transfer Task to another

- src/main/java/com/compuware/ispw/restapi/action/GetContainerListAction.java
ISPW Operations Plugin - container list API returns incorrect list of
containers
https://agile.compuware.com/browse/CWE-143709
> CWE-143709: ISPW Operations Plugin - container list API returns incorrect list of containers

- src/main/java/com/compuware/ispw/model/rest/WorkListInfo.java
- src/main/java/com/compuware/ispw/model/rest/WorkListResponse.java
- src/main/java/com/compuware/ispw/restapi/action/GetWorkListAction.java
- src/main/java/com/compuware/ispw/restapi/action/IAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
- src/main/webapp/help-ispwRequestBody.html
https://agile.compuware.com/browse/CWE-144407
> CWE-144407: Jenkins Operations Plugin - Get Worklist

- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/action/RemoveFromReleaseAction.java
- src/main/webapp/help-ispwRequestBody.html
https://agile.compuware.com/browse/CWE-142020
> CWE-142020: ISPW Operations Jenkins Plugin - remove from release

- src/main/java/com/compuware/ispw/restapi/action/FallbackAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/FallbackReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/webapp/help-ispwRequestBody.html
https://agile.compuware.com/browse/CWE-141527
> CWE-141527: Jenkins Operations Plugin - Fallback Release/ Assignment

- src/main/java/com/compuware/ispw/model/rest/TaskLoadResponse.java
- src/main/java/com/compuware/ispw/restapi/action/IAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/action/TaskLoadAction.java
- src/main/webapp/help-ispwRequestBody.html
https://agile.compuware.com/browse/CWE-143293
> CWE-143293: Jenkins Operations Plugin - Task Load API

- src/main/java/com/compuware/ispw/restapi/Constants.java
- src/main/java/com/compuware/ispw/restapi/IspwContextPathBean.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/action/GenericPostAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/java/com/compuware/ispw/restapi/action/SetOperationAction.java
- src/main/java/com/compuware/ispw/restapi/util/ReflectUtils.java
- src/main/webapp/help-ispwAction.html
- src/main/webapp/help-ispwRequestBody.html
add set operations-unlock,lock,restart,terminate,restart,hold,release,delete,approve,deny,reset
> Cwe 141525  add set operations-unlock,lock,restart,terminate,restart,hold,release,delete,approve,deny,reset

- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/SetOperationAction.java
- src/main/resources/com/compuware/ispw/restapi/IspwRestApiRequestStep/config.jelly
> CWE-146166 - Add 'skip polling' into pipeline script for ispw operations

- src/main/java/com/compuware/ispw/model/rest/BuildResponse.java
- src/main/java/com/compuware/ispw/restapi/HttpRequestExecution.java
- src/main/java/com/compuware/ispw/restapi/IspwContextPathBean.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/BuildAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/BuildReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/BuildTaskAction.java
- src/main/java/com/compuware/ispw/restapi/action/IspwCommand.java
- src/main/webapp/help-ispwAction.html
- src/main/webapp/help-ispwRequestBody.html
ISPW/Git - Add Build function to ISPW Operations Plugin in Jenkins
https://agile.compuware.com/browse/CWE-151163
> CWE-151163:

- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
https://agile.compuware.com/browse/CWE-151222
> CWE-151222: ISPW/GIT---CLI-Logging Improvements

- src/main/java/com/compuware/ispw/git/CliExecutor.java
- src/main/java/com/compuware/ispw/git/GitToIspwPublish.java
- src/main/java/com/compuware/ispw/git/GitToIspwPublishStep.java
Deleting files from a git repository and syncing the changes to ISPW
does not remove the component in ISPW
https://agile.compuware.com/browse/CWE-153949
> CWE-153949

- src/main/java/com/compuware/ispw/git/CliExecutor.java
- src/main/java/com/compuware/ispw/git/GitToIspwConstants.java
Rename '-jenkinsWorkspaceJobPath' to '-gitLocalPath' in ISPW CLI
https://agile.compuware.com/browse/CWE-155020
> CWE-155020

- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
> CWE-157285 Jenkins pipeline perform BuildAssignment with no impacts

- README.md
Document the GIT Project for the DevOps page
https://agile.compuware.com/browse/CWE-156696
> CWE-156696: document the git project for the dev ops page

- src/main/java/com/compuware/ispw/restapi/HttpRequestExecution.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
> CWE-157193 GenerateTasksInAssignmentAction failing with a

- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/IBuildAction.java
- src/main/java/com/compuware/ispw/restapi/action/RemoveFromReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/TransferTaskAction.java
> CWE-158726 ISPW operations plugin reports failed build as successful,

- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/BuildAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/BuildReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/BuildTaskAction.java
- src/main/java/com/compuware/ispw/restapi/action/DeployAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/DeployReleaseAction.java
- src/main/java/com/compuware/ispw/restapi/action/GenerateTasksInAssignmentAction.java
- src/main/java/com/compuware/ispw/restapi/action/GenerateTasksInReleaseAction.java
Console be consistent at messaging.
https://agile.compuware.com/browse/CWE-158094
> Cwe 158094 - jenkins operations plugin - have the jenkins and topaz console be consistent at messaging

- README.md
- pom.xml
- src/main/java/com/compuware/ispw/git/CustomGitChangeSetList.java
- src/main/java/com/compuware/ispw/git/GitToIspwPublishStep.java
- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
- src/main/java/com/compuware/ispw/restapi/action/IBuildAction.java
- src/test/java/com/compuware/ispw/git/GitToIspwUtilsTest.java
ISPW/Git - IMPLEMENTATION-Make the Jenkins build process re-runnable
https://agile.compuware.com/browse/CWE-161627
> CWE-161627

- src/main/java/com/compuware/ispw/restapi/action/IBuildAction.java
> CWE-162687 file is created at the beginning of sync step, it should not

- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
action null; Enforce level check for New API
> Cwe 166857 NPE + compatible with older TPZ system

- .gitignore
- README.md
- dev/example/pipeline.mb.Jenkinsfile.txt
- dev/example/pipeline.webhook.txt
- pom.xml
- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/util/ReflectUtils.java
CWE-165779 - ECLIPSE: BUILD to support Webhooks instead of polling for TTT file;
Also for Generate, Promote, Regress and Deploy.
> Cwe 167962 the webhook callback originally supported in ispw operation plugin no longer works

- README.md
- src/main/java/com/compuware/ispw/git/CliExecutor.java
- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
- src/test/java/com/compuware/ispw/git/GitToIspwUtilsTest.java
Escape the Git Repository URL correctly for bitbucket
https://agile.compuware.com/browse/CWE-167778
> CWE-167778: Escape bitbucket uri

- README.md
- src/main/java/com/compuware/ispw/restapi/HttpRequestExecution.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/util/RestApiUtils.java
> CWE-166655 NPE in build step when nothing to build and host connection

- src/main/java/com/compuware/ispw/model/rest/TaskInfo.java
now provided in the build response (Part 2 of 2)
https://zsojira.bmc.com/browse/ZENG-170958
> Zeng 170958   -  rest api and jenkins utilize the container name that is now provided in the build response (part 2 of 2)

- src/main/java/com/compuware/ispw/git/GitToIspwPublish.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequest.java
- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
- src/main/java/com/compuware/ispw/restapi/action/IAction.java
With buildAutomatically set to true, get message "Level must be set" and
build fails when nothing to build
https://agile.compuware.com/browse/CWE-169885
> CWE-169885: Re-work flow during automatic operation when nothing synced

- compile.bat
- pom.xml
- src/main/java/com/compuware/ispw/git/CliExecutor.java
> ZENG-227661 Maven fails when use Compuware Common Configure plugin 1.0.12-SNAPSHOT

- src/main/java/com/compuware/ispw/restapi/IspwRestApiRequestStep.java
> ZENG-170958-Update Jenkins Build messages

- pom.xml
update credential plugin dependency.
> ZENG-226796 Update dependencies of the Jenkins Credential Plugin for the

- src/main/webapp/help-ispwRequestBody.html
> ZENG-170691 buildAutomatically is mutually exclusive with other

- dev/docker/ispw_jenkins_with_cli/Dockerfile
- dev/docker/ispw_jenkins_with_cli/LICENSE
- dev/docker/ispw_jenkins_with_cli/README.md
- dev/docker/ispw_jenkins_with_cli/dist/download.sh
- dev/docker/ispw_jenkins_with_cli/dist/placeholder.txt
- dev/docker/ispw_jenkins_with_cli/docker-compose.yml
- dev/docker/ispw_jenkins_with_cli/plugins.txt
- dev/docker/ispw_jenkins_with_cli/readme.txt
> build jenkins with ispw cli included

- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
> Add certificate credentials to the Credentials option

- src/main/java/com/compuware/ispw/git/CliExecutor.java
- src/main/java/com/compuware/ispw/git/GitToIspwConstants.java
- src/main/java/com/compuware/ispw/git/GitToIspwPublish.java
- src/main/java/com/compuware/ispw/git/GitToIspwPublishStep.java
- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
- src/main/java/com/compuware/ispw/git/IGitToIspwPublish.java
- src/main/resources/com/compuware/ispw/git/GitToIspwPublish/config.jelly
- src/main/resources/com/compuware/ispw/git/GitToIspwPublishStep/config.jelly
- src/main/webapp/help-gitIspwSubApplication.html
> Added support of Arrakis for ISPW Sync

- src/main/java/com/compuware/ispw/model/request/Assignment.java
- src/main/java/com/compuware/ispw/model/rest/AssignmentInfo.java
- src/main/java/com/compuware/ispw/model/rest/DeploymentPackageInfo.java
- src/main/webapp/help-ispwRequestBody.html
Zeng 250416 provides the ability to create a sandbox code line in the APIs
> Zeng 250416 provide the ability to create a sandbox codeline in the apis

- src/main/java/com/compuware/ispw/git/GitToIspwPublishStep.java
- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
This PR will fix the issue where the multibranch pipeline isn't able to sync failured builds from git to ISPW
```[tasklist]
```
> Load changes from prior failed jobs

- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
> Fixed findbugs errors

- src/main/webapp/help-ispwRequestBody.html
> help changes for close action

- src/main/resources/com/compuware/ispw/restapi/IspwRestApiRequest/config.jelly
- src/main/resources/com/compuware/ispw/restapi/IspwRestApiRequestStep/config.jelly
> updated !!

- src/main/java/com/compuware/ispw/restapi/IspwContextPathBean.java
- src/main/java/com/compuware/ispw/restapi/action/GetAssignmentInfoAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetAssignmentTaskListAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetContainerListAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetDeploymentListAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetReleaseInfoAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetReleaseTaskGenerateListingAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetReleaseTaskInfoAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetReleaseTaskListAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetSetInfoAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetSetTaskListAction.java
- src/main/java/com/compuware/ispw/restapi/action/GetWorkListAction.java
- src/main/java/com/compuware/ispw/restapi/action/IAction.java
- src/main/java/com/compuware/ispw/restapi/action/LoadGenParmAjaxRequest.java
- src/main/webapp/help-ispwRequestBody.html
- src/test/java/com/compuware/ispw/restapi/util/RestApiUtilsTest.java
Please describe your pull request here. -->
> Fixed the rtConfig issue

- pom.xml
https://jira.zeng.bmc.com/browse/ZENG-366053
> Fix vulnerability reported in commons-collections 3.2.1

- README.md
- src/main/webapp/help-ispwRequestBody.html
- Add pending status for Deployment List filter
> Add pending status for Deployment List filter

- src/main/java/com/compuware/ispw/git/GitToIspwUtils.java
- src/main/java/com/compuware/ispw/restapi/action/LoadGenParmAjaxRequest.java
- src/main/java/com/compuware/ispw/restapi/action/ReleaseDeployOperation.java
> Zeng 384049 bug fix
